import React from 'react';
import { StyleSheet, View, Text, TouchableOpacity, Modal, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS, TYPOGRAPHY, SPACING, BORDER_RADIUS } from '../constants/theme';

interface Change {
  lineNumber: number;
  before: string;
  after: string;
  description: string;
}

interface DiffViewerProps {
  isOpen: boolean;
  onClose: () => void;
  fileName: string;
  changes: Change[];
  onApply: () => void;
}

// Removing hardcoded DIFF_DATA

const DiffViewer = ({ isOpen, onClose, fileName, changes, onApply }: DiffViewerProps) => {
  return (
    <Modal visible={isOpen} animationType="slide" transparent={false}>
      <SafeAreaView style={styles.container}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.headerRow}>
            <Text style={styles.headerTitle}>Review Changes</Text>
            <TouchableOpacity onPress={onClose}>
              <Text style={styles.closeIcon}>✕</Text>
            </TouchableOpacity>
          </View>
          <Text style={styles.headerSubtitle}>{fileName} · {changes.length} changes</Text>
        </View>

        {/* Diff Area */}
        <ScrollView style={styles.diffArea}>
          {changes.map((change, index) => (
            <View key={index} style={styles.changeBlock}>
              <Text style={styles.changeDescription}>{change.description}</Text>
              
              <View style={[styles.lineWrapper, styles.removedLine]}>
                 <Text style={[styles.marker, styles.removedText]}>−</Text>
                 <Text style={[styles.lineNo]}>{change.lineNumber}</Text>
                 <Text style={[styles.codeText, styles.removedText]}>{change.before}</Text>
              </View>

              <View style={[styles.lineWrapper, styles.addedLine]}>
                 <Text style={[styles.marker, styles.addedText]}>+</Text>
                 <Text style={[styles.lineNo]}>{change.lineNumber}</Text>
                 <Text style={[styles.codeText, styles.addedText]}>{change.after}</Text>
              </View>
            </View>
          ))}

          {changes.length === 0 && (
            <View style={styles.emptyState}>
              <Text style={styles.emptyText}>No specific line changes identified.</Text>
            </View>
          )}

          {/* AI Explanation Card */}
          <View style={styles.explanationCard}>
            <Text style={styles.explanationText}>
              These changes were generated by AI based on your request. Please review the line-by-line diff above before applying.
            </Text>
          </View>
        </ScrollView>

        {/* Bottom Actions */}
        <View style={styles.bottomActions}>
          <TouchableOpacity 
            style={[styles.actionButton, styles.applyButton]} 
            onPress={onApply}
          >
            <Text style={styles.applyButtonText}>✓ Apply</Text>
          </TouchableOpacity>
          <TouchableOpacity style={[styles.actionButton, styles.modifyButton]}>
            <Text style={styles.modifyButtonText}>✏ Modify</Text>
          </TouchableOpacity>
          <TouchableOpacity style={[styles.actionButton, styles.cancelButton]} onPress={onClose}>
            <Text style={styles.cancelButtonText}>✕ Cancel</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    </Modal>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050505',
  },
  header: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1a1a1a',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  closeIcon: {
    color: '#666',
    fontSize: 18,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFF',
    letterSpacing: -0.2,
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#333',
    marginTop: 4,
  },
  diffArea: {
    flex: 1,
    paddingVertical: 12,
  },
  changeBlock: {
    marginBottom: 20,
    backgroundColor: '#0a0a0a',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#111',
    marginHorizontal: 16,
  },
  changeDescription: {
    color: '#888',
    fontSize: 12,
    padding: 12,
    backgroundColor: '#0d0d0d',
  },
  lineWrapper: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  removedLine: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
  },
  addedLine: {
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
  },
  marker: {
    width: 15,
    fontSize: 14,
    fontFamily: 'monospace',
    fontWeight: '700',
  },
  lineNo: {
    width: 30,
    color: '#444',
    fontSize: 12,
    fontFamily: 'monospace',
  },
  codeText: {
    flex: 1,
    fontSize: 13,
    fontFamily: 'monospace',
    letterSpacing: 0.2,
  },
  removedText: {
    color: COLORS.accent.red,
  },
  addedText: {
    color: COLORS.accent.green,
  },
  neutralText: {
    color: '#555',
  },
  emptyState: {
    padding: 40,
    alignItems: 'center',
  },
  emptyText: {
    color: '#444',
    fontSize: 14,
  },

  explanationCard: {
    marginHorizontal: 24,
    marginTop: 24,
    backgroundColor: 'rgba(59, 130, 246, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.15)',
    borderRadius: 14,
    padding: 20,
  },
  explanationText: {
    fontSize: 13,
    color: '#AAA',
    lineHeight: 20,
  },
  bottomActions: {
    flexDirection: 'row',
    padding: 20,
    gap: 12,
    paddingBottom: 40,
    backgroundColor: '#050505',
    borderTopWidth: 1,
    borderTopColor: '#080808',
  },
  actionButton: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  applyButton: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.2)',
  },
  applyButtonText: {
    color: COLORS.accent.green,
    fontSize: 13,
    fontWeight: '700',
  },
  modifyButton: {
    backgroundColor: '#0D0D0D',
    borderWidth: 1,
    borderColor: '#181818',
  },
  modifyButtonText: {
    color: '#666',
    fontSize: 13,
    fontWeight: '600',
  },
  cancelButton: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.15)',
  },
  cancelButtonText: {
    color: COLORS.accent.red,
    fontSize: 13,
    fontWeight: '700',
  },
});

export default DiffViewer;
